// Re-export project frontmatter data for use in manifest
// This will be replaced by .pdsl Vite plugin loading when DSL is fully active

import type { ProjectFrontmatter } from "@/dsl/frontmatter";

export const projectMeta: Record<string, ProjectFrontmatter> = {
  rxcompose: {
    type: "library",
    index: "01",
    title: "RxCompose",
    subtitle: "RxSwift 기반 단방향 아키텍처 라이브러리 (iOS 13+, RxSwift 6.9+)",
    period: "2025.02.17 ~ 2025.03.30",
    team: "iOS 1명",
    role: "iOS 개발",
    description:
      "ReactorKit은 Effect 개념이 없기 때문에 상태 변화에 따른 후속 작업을 정의하기 어렵다는 문제점이 있습니다. 이러한 문제점을 해결하기 위해, TCA의 단방향 아키텍처 매커니즘을 RxSwift 환경에 맞춰 구현했습니다. 실제 ShowPot이라는 프로젝트에 활용하여 적용 가능성 테스트 및 개선사항을 점검했습니다.",
    techStack: ["Swift Package Manager", "CocoaPods"],
    githubUrl: "https://github.com/ShapeKim98/RxCompose",
    screenshotLabel: "RxCompose 아키텍처 다이어그램 스크린샷",
    hideScreenshot: true,
    divider: { bg: false },
  },
  filtee: {
    type: "project",
    index: "02",
    title: "Filtee",
    subtitle:
      "나만의 필터를 만들고, 공유하고, 필터 작가와 소통하는 감성 필터 플랫폼 (iOS 16+)",
    period: "2025.05.11 ~ 2025.06.12",
    team: "서버 1명, 디자이너 1명, iOS 1명",
    role: "iOS 개발",
    description:
      "사용자가 직접 필터를 제작하고 공유하며, 필터 작가와 소통할 수 있는 플랫폼입니다.",
    techStack: [
      "SwiftUI",
      "Alamofire",
      "Swift Concurrency",
      "Nuke",
      "SocketIO",
      "KakaoSDK",
      "Firebase",
      "Metal",
    ],
    githubUrl: "https://github.com/ShapeKim98/Filtee",
    screenshotLabel: "Filtee 앱 스크린샷",
    screenshot: "@/image/필티표지.png",
  },
  pokit: {
    type: "project",
    index: "03",
    title: "Pokit",
    subtitle: "간편 링크 아카이빙 앱 (iOS 16+)",
    period: "2024.05.11 ~ 2024.08.27 (유지보수 중)",
    team: "PM 1명, 디자이너 2명, 서버 2명, iOS 2명, 안드로이드 2명",
    role: "iOS 개발",
    description:
      "간편하게 링크를 저장하고, 분류하고, 잊지 않고 볼 수 있도록 도와주는 서비스입니다.",
    techStack: [
      "SwiftUI",
      "TCA",
      "Modular Architecture",
      "Tuist",
      "Github Actions",
      "Fastlane",
      "Moya",
      "Nuke",
      "KakaoSDK",
      "Firebase",
      "Share Extension",
    ],
    githubUrl: "https://github.com/YAPP-Github/Pokit-iOS",
    appStoreUrl:
      "https://apps.apple.com/kr/app/pokit-%ED%8F%AC%ED%82%B7-%EA%B0%84%ED%8E%B8-%EB%A7%81%ED%81%AC-%EC%95%84%EC%B9%B4%EC%9D%B4%EB%B9%99-%EC%95%B1/id6514313808",
    screenshotLabel: "Pokit 앱 스크린샷",
    screenshot: "@/image/포킷표지.png",
  },
  interest: {
    type: "project",
    index: "04",
    title: "인터레스트",
    subtitle: "사용자 맞춤 인터벌 트레이닝 (iOS 17+)",
    period: "2023.11 ~ 2024.04",
    team: "iOS 5명",
    role: "iOS 개발, 디자인",
    description:
      "사용자 맞춤 인터벌 트레이닝을 가이드 해주는 서비스입니다.",
    techStack: [
      "SwiftUI",
      "MVVM",
      "Clean Architecture",
      "Tuist",
      "HealthKit",
      "WatchConnectivity",
      "WatchKit",
      "SwiftData",
    ],
    githubUrl: "https://github.com/TEAM-ALOM/interest-iOS",
    screenshotLabel: "인터레스트 앱 스크린샷",
    screenshot: "@/image/인터레스트표지.png",
  },
  showpot: {
    type: "project",
    index: "04",
    title: "ShowPot",
    subtitle: "내한 공연 정보, 티켓팅 알림 (iOS 16+)",
    period: "2025.03.29 ~ 2025.04.14",
    team: "PM 1명, 디자이너 2명, 서버 2명, iOS 1명, 안드로이드 2명",
    role: "iOS 개발",
    description: "내한 공연 정보 제공 및 티켓팅 알림 서비스입니다.",
    techStack: [
      "UIKit",
      "SnapKit",
      "RxSwift",
      "MVI",
      "Clean Architecture",
      "Kingfisher",
      "Alamofire",
      "Swift Concurrency",
      "Swift Dependencies",
      "KakaoSDK",
      "Firebase",
      "SwiftJWT",
    ],
    githubUrl: "https://github.com/AlreadyTakenSeat/ShowPot-iOS",
    screenshotLabel: "ShowPot 앱 스크린샷",
    screenshot: "@/image/쇼팟표지.png",
  },
};
